.github/workflows/build-back.yml, .github/workflows/build-front.yml
- added context value
closes #42
=> bug #42: fixed build failure

fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/MobileDropdown.tsx
bugfix: changed buttons appearance condition
bugfix: added deputy headman downgrade button in dropdown menu
=> bugfix #31: added deputy headman downgrade button in dropdown menu 

fictadvisor-api/src/v2/api/controllers/DisciplineController.ts, fictadvisor-api/src/v2/api/dtos/QueryAllDisciplinesDTO.ts, fictadvisor-api/src/v2/api/pipes/QueryAllDisciplinesPipe.ts, fictadvisor-api/src/v2/api/responses/DisciplineResponse.ts, fictadvisor-api/src/v2/api/responses/TeacherResponse.ts, fictadvisor-api/src/v2/api/services/DisciplineService.ts, fictadvisor-api/src/v2/api/services/GroupService.ts, fictadvisor-api/src/v2/api/services/PollService.ts, fictadvisor-api/src/v2/api/services/ScheduleService.ts, fictadvisor-api/src/v2/api/services/UserService.ts, fictadvisor-api/src/v2/database/repositories/DisciplineRepository.ts, fictadvisor-api/src/v2/mappers/DisciplineMapper.ts, fictadvisor-api/src/v2/modules/DisciplineModule.ts, fictadvisor-api/src/v2/modules/TeacherModule.ts, fictadvisor-api/src/v2/utils/QueryAllDTO.ts
- created getStrictSearch in DatabaseUtils
- created getAll in DisciplineController
- created getAll in DisciplineService
- created getDisciplinesForAdmin in DisciplineMapper
- created count in DisciplineRepository
- created DisciplineAdminResponse and DisciplinesResponse
- created QueryAllDisciplinesDTO
- created QueryAllDisciplinesPipe
- created ShortTeacherResponse
closes #842
=> feature #842: Implemented an endpoint to receive all disciplines

fictadvisor-api/src/v2/api/controllers/RoleController.ts, fictadvisor-api/src/v2/api/controllers/UserController.ts, fictadvisor-api/src/v2/api/dtos/QueryAllUsersDTO.ts, fictadvisor-api/src/v2/api/responses/UsersResponse.ts, fictadvisor-api/src/v2/api/services/UserService.ts, fictadvisor-api/src/v2/database/repositories/UserRepository.ts, fictadvisor-api/src/v2/mappers/UserMapper.ts, fictadvisor-api/src/v2/security/PERMISSION.ts
- added users.get permission
- added getAll method in UserController
- added getAll method in UserMapper
- added getAll method in UserService
- added count method in UserRepository
- updated findMany method in userRepository
- created QueryAllUsersDTO and SortQAUParam
- created UsersResponse
- updated validationOptionMsg in GLOBALS (by @f-ogoog)
closes #862
=> feature #862: Added the ability to get all users

fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule-header/ScheduleHeader.tsx
- ensured "Сьогодні" button is always available on Schedule Page
closes #18
=> enhancement #18: ensuring "Сьогодні" button availability

fictadvisor-api/src/v2/api/controllers/TeacherController.ts, fictadvisor-api/src/v2/api/responses/TeacherWithRolesAndContactsResponse.ts, fictadvisor-api/src/v2/api/services/TeacherService.ts, fictadvisor-api/src/v2/security/PERMISSION.ts
- added disconnectTeacherFromCathedra in TeacherService
- added documentation in TeacherController
closes #858
=> feature #858: disconnecting teachers from cathedras

fictadvisor-api/src/v2/api/controllers/GroupController.ts, yarn.lock
- updated removeStudent endpoint
- updated getUnverifiedStudents endpoint
- updated getGroupList endpoint
closes #57
=> documentation #57: updated swagger for groups

fictadvisor-api/src/v2/api/controllers/GroupController.ts, fictadvisor-api/src/v2/api/dtos/EmailDTO.ts, fictadvisor-api/src/v2/api/dtos/RoleDTO.ts
- updated addUnregistered endpoint
- updated verifyStudent endpoint
- updated moderatorSwitch endpoint
closes #58
=> documentation #58: updated swagger for groups

fictadvisor-api/src/v2/api/controllers/UserController.ts, fictadvisor-api/src/v2/api/dtos/TelegramDTO.ts, fictadvisor-api/src/v2/api/responses/RoleWithStudentResponse.ts, yarn.lock
- updated linkTelegram endpoint
- updated uploadAvatar endpoint
- updated deleteAvatar endpoint
- updated changeGroup endpoint
closes #56
=> documentation #56: updated swagger for users

fictadvisor-api/src/v2/api/services/UserService.ts
- changed method to check for existing specific semester
closes #76
=> bugfix #76: fixed bug with inability to pick selective disciplines

fictadvisor-web/src/components/pages/account-page/AccountPage.tsx, fictadvisor-web/src/utils/createQueryString.ts
- fixed tabs navigation
- created createQueryString method to manage tabs and query mutating
closes #124
=> bug #124: fixed mobile header account tabs navigation

fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/MobileDropdown.tsx
- fixed the vertical command menu that was overlapping footer on the "Група" page 
closes #6
=> bug #6: fixed overlay  menu on the "Група" page

fictadvisor-web/src/components/common/ui/icon-button-mui/variants/ExportButton/ExportButton.stories.ts, fictadvisor-web/src/components/common/ui/icon-button-mui/variants/ExportButton/ExportButton.styles.ts, fictadvisor-web/src/components/common/ui/icon-button-mui/variants/ExportButton/ExportButton.tsx, fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx, fictadvisor-web/src/lib/api/group/GroupAPI.ts, fictadvisor-web/src/lib/api/group/types/ExportGroupStudents.ts
- added icon button that triggers endpoint on the back-end
- added tooltip to the button
closes #52
=> feature #52: export group list

fictadvisor-api/src/v2/api/services/GroupService.ts, fictadvisor-web/src/components/pages/account-page/components/group-tab/GroupTab.styles.ts, fictadvisor-web/src/components/pages/account-page/components/group-tab/GroupTab.tsx, fictadvisor-web/src/components/pages/schedule-page/calendar-section/CalendarSection.tsx, fictadvisor-web/src/lib/api/group/GroupAPI.ts
- added restriction for group captain
- deleted selective after the leaving
closes #54
=> feature #54: added leave group on account page

fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/PersonalTeacherTabs.tsx, fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.styles.ts, fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.tsx, fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/components/ComplaintPopupContent.styles.ts, fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/components/ComplaintPopupContent.tsx, fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/validation/index.ts
- designed dropdown options
- labels and description for fields
closes #137
=> bug #137: Fix complaint form

fictadvisor-api/src/v2/api/controllers/GroupController.ts, fictadvisor-api/src/v2/api/services/GroupService.ts
- added returning a group in group service and returning a mapped group in controller
- added a group response for swagger
closes #60
=> enhancement #60: add-a-response-after-deleting-a-group

fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.styles.ts, fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.tsx, fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/types/CheckboxesDropdown.ts
- switched autocomplete to select
closes #144
=> feature #144: fix dropdown #2

fictadvisor-api/src/v2/api/controllers/TeacherController.ts, fictadvisor-api/src/v2/api/pipes/SubjectByIdPipe.ts, fictadvisor-api/src/v2/api/responses/DisciplineTeacherAndSubjectResponse.ts, fictadvisor-api/src/v2/api/responses/GroupResponse.ts, fictadvisor-api/src/v2/api/responses/RoleWithStudentResponse.ts, fictadvisor-api/src/v2/api/responses/StudentResponse.ts, fictadvisor-api/src/v2/api/responses/SubjectsResponse.ts, fictadvisor-api/src/v2/api/responses/TeacherRolesResponse.ts, fictadvisor-api/src/v2/api/responses/TeacherWithContactAndRoleResponse.ts, fictadvisor-api/src/v2/api/responses/TeacherWithSubjectResponse.ts, fictadvisor-api/src/v2/mappers/StudentMapper.ts
- updated getTeacherRoles endpoint
- updated getSubjects endpoint
- updated getDisciplines endpoint
- updated getSubject endpoint
- updated getTeacher endpoint
- updated response body in changeGroup endpoint
closes #84
=> documentation #84: updated swagger for teachers

fictadvisor-api/prisma/migrations/20240113093650_update_of_event_storing/migration.sql, fictadvisor-api/prisma/schema.prisma, fictadvisor-api/src/v2/api/controllers/ScheduleController.ts, fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts, fictadvisor-api/src/v2/api/services/ScheduleService.spec.ts, fictadvisor-api/src/v2/api/services/ScheduleService.ts, fictadvisor-api/src/v2/database/entities/DbEvent.ts, fictadvisor-api/src/v2/utils/date/DateModule.ts, fictadvisor-api/src/v2/utils/date/DateUtils.ts, fictadvisor-api/src/v2/utils/parser/RozParser.ts, fictadvisor-api/src/v2/utils/parser/ScheduleParser.ts
- Added eventsAmount int field
- Added teacherForceChanges boolean field
- Added isCustom boolean field
- Updated integration tests 
- Updated unit tests
- Updated logic of get, create, update events 
- Updated logic of parsing 
- Updated logic of eventInfo 
- Added check logic for teacher change 
- Added idCustom flag for custom events
- Created DateUtils for calculations 
closes #98 #103
=> migration #98: updated events table for new event storing logic

fictadvisor-api/src/v2/api/dtos/QueryAllDisciplineTeacherForPollDTO.ts, fictadvisor-api/src/v2/api/services/PollService.ts, fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.stories.tsx, fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.styles.ts, fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.tsx, fictadvisor-web/src/components/pages/search-pages/poll-search-form/PollSearchForm.module.scss, fictadvisor-web/src/components/pages/search-pages/poll-search-form/PollSearchForm.styles.ts, fictadvisor-web/src/components/pages/search-pages/poll-search-form/PollSearchForm.tsx, fictadvisor-web/src/components/pages/search-pages/poll-search-form/constants.ts, fictadvisor-web/src/components/pages/search-pages/poll-search-form/index.ts, fictadvisor-web/src/components/pages/search-pages/poll-search-form/types/index.ts, fictadvisor-web/src/components/pages/search-pages/poll-teachers-page/PollTeacherPage.styles.ts, fictadvisor-web/src/components/pages/search-pages/poll-teachers-page/PollTeacherPage.tsx, fictadvisor-web/src/components/pages/search-pages/poll-teachers-page/components/PollTeacherSearchList.styles.ts, fictadvisor-web/src/components/pages/search-pages/poll-teachers-page/components/PollTeacherSearchList.tsx, fictadvisor-web/src/lib/api/instance.ts, fictadvisor-web/src/lib/api/poll/PollAPI.ts
=> bug #22: fixed survey page

fictadvisor-web/src/app/admin/subjects/create/page.tsx, fictadvisor-web/src/app/admin/subjects/edit/[subjectId]/page.tsx, fictadvisor-web/src/app/admin/subjects/page.tsx, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-create-page/AdminSubjectCreatePage.styles.ts, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-create-page/AdminSubjectCreatePage.tsx, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-create-page/index.ts, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-edit-page/AdminSubjectEditPage.styles.ts, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-edit-page/AdminSubjectEditPage.tsx, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-edit-page/index.ts, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/AdminSubjectSearchPage.styles.ts, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/AdminSubjectSearchPage.tsx, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-search/AdminSubjectSearch.styles.ts, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-search/AdminSubjectSearch.tsx, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-search/index.ts, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-table/AdminSubjectTable.styles.ts, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-table/AdminSubjectTable.tsx, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-table/index.ts, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/index.ts, fictadvisor-web/src/components/pages/search-pages/subject-search/SubjectSearchPage.tsx, fictadvisor-web/src/lib/api/subject/SubjectAPI.ts, fictadvisor-web/src/lib/api/subject/types/GetListOfSubjectsResponse.ts, fictadvisor-web/src/lib/api/teacher/types/GetTeachersResponse.ts, fictadvisor-web/src/types/api.ts
- added admin subject search page
- added admin subject edit page
- added admin subject create page
- added missing endpoints to SubjectAPI
closes #35
=> feature #35: added admin subject flow

fictadvisor-web/src/app/password-recovery/[token]/page.tsx, fictadvisor-web/src/components/pages/account-page/components/security-tab/components/change-password-form/ChangePasswordForm.tsx, fictadvisor-web/src/components/pages/password-recovery/create-password-page/CreatePasswordPage.tsx, fictadvisor-web/src/components/pages/password-recovery/create-password-page/components/create-password-form/CreatePasswordForm.tsx, fictadvisor-web/src/components/pages/password-recovery/validation/changePasswordValidationSchema.ts, fictadvisor-web/src/components/pages/password-recovery/validation/createPasswordValidationSchema.ts, fictadvisor-web/src/components/pages/register/register-page/components/register-form/validation/index.ts
bug #145: reset password is not working
- fixed bug with transfer token in components
- fixed bug with changing the password after sending an email message
- fixed bug with changing the password in personal account
- rename passwordValidationSchema to changePasswordValidationSchema
closes #145
=> bug #145: reset password is not working

fictadvisor-web/src/components/pages/account-page/components/group-tab/GroupTab.tsx, fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.styles.ts, fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx, fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/types/index.ts
- reordered the buttons
- changed their style
- added onclick icon changing event on sort button
closes #136
=> bug #136: fixed group management buttons on desktop

fictadvisor-api/prisma/migrations/20240122125814_add_division_to_cathedra/migration.sql, fictadvisor-api/prisma/schema.prisma, fictadvisor-api/src/v2/api/dtos/CreateCathedraDTO.ts, fictadvisor-api/src/v2/api/dtos/UpdateCathedraDTO.ts, fictadvisor-api/src/v2/api/responses/CathedraResponse.ts, fictadvisor-api/src/v2/database/entities/DbCathedra.ts, fictadvisor-api/src/v2/mappers/CathedraMapper.ts, fictadvisor-api/src/v2/mappers/DisciplineTeacherMapper.ts, fictadvisor-api/src/v2/mappers/TeacherMapper.ts
- Added division text field
- Enriched CRUD endpoints for cathedra
- Enriched teacher mappers
closes #113
=> migration #113: added division field to cathedras table

fictadvisor-web/src/components/pages/account-page/components/general-tab/components/contacts-block/components/ContactItem.tsx
- fixed remove social media link button
closes #15
=> bug #15: Fix remove social media link

fictadvisor-api/prisma/migrations/20240124111616_add_info_about_profession_of_teacher/migration.sql, fictadvisor-api/prisma/schema.prisma, fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts
- added AcademicStatus, ScientificDegree, Position enums
- added academicStatus, scientificDegree, position fields
closes #106
=> migration #106: added info about profession of teacher

.github/pull-request-template.md
=> chore: added pull request template

fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/text-area/TextArea.styles.ts, fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/text-area/TextArea.tsx
- Added error states to about discipline and about event fields on a schedule page
closes #19
=> enhancement #19: Add error states to about discipline and about event fields on a schedule page

fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/editing-column/EditingColumn.styles.ts
- fixed gaps
- added typography
closes #147
=> bug #147: aligned change button relatively to its window

fictadvisor-web/src/app/admin/users/create/page.tsx, fictadvisor-web/src/app/admin/users/edit/[userId]/page.tsx, fictadvisor-web/src/app/admin/users/page.tsx, fictadvisor-web/src/components/pages/admin/admin-user/constants/UserStateOptions.ts, fictadvisor-web/src/components/pages/admin/admin-user/create-user-page/AdminUserCreate.styles.ts, fictadvisor-web/src/components/pages/admin/admin-user/create-user-page/AdminUserCreate.tsx, fictadvisor-web/src/components/pages/admin/admin-user/create-user-page/index.ts, fictadvisor-web/src/components/pages/admin/admin-user/edit-user-page/EditUserPage.styles.ts, fictadvisor-web/src/components/pages/admin/admin-user/edit-user-page/EditUserPage.tsx, fictadvisor-web/src/components/pages/admin/admin-user/edit-user-page/index.ts, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/AdminUserSearch.styles.ts, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/AdminUserSearch.tsx, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/components/header-user-search/HeaderUserSearch.styles.ts, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/components/header-user-search/HeaderUserSearch.tsx, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/components/header-user-search/index.ts, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/components/users-list/UsersList.styles.ts, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/components/users-list/UsersList.tsx, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/components/users-list/index.ts, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/constants/Options.ts, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/constants/UserInitialValues.ts, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/constants/UserSearchConstants.ts, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/index.ts, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/types/HeaderUserSearch.ts, fictadvisor-web/src/lib/api/instance.ts, fictadvisor-web/src/lib/api/user/UserAPI.ts, fictadvisor-web/src/lib/api/user/types/ChangeUserBody.ts, fictadvisor-web/src/lib/api/user/types/CreateUserBody.ts, fictadvisor-web/src/lib/api/user/types/GetAllResponse.ts, fictadvisor-web/src/types/user.ts
- added admin user search page
- added admin user edit page
- added admin user create page
- added missing endpoints to UserAPI
closes #25
=> feature #25 added admin user flow

fictadvisor-web/src/app/layout.tsx, fictadvisor-web/src/lib/services/telegram/TelegramService.ts
- fixed telegram auth bug
closes #176
=>  bug #176: fixed telegram auth bug

fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.tsx
- added use resetForm function from Formik
closes #156
=> bug #156: reset complaint form

fictadvisor-api/prisma/migrations/20240127110546_main_page/migration.sql, fictadvisor-api/prisma/schema.prisma
- created migration with PageText model to store text from main page
closes #107
=> migration #107: Added table for storing texts 

fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/utils/prepareData.ts, fictadvisor-web/src/lib/api/schedule/types/DetailedEventBody.ts
- Added disciplineId in request payload after updating event
closes #146
=> enhancement #146: Add invisible disciplineId field in schedule event form

fictadvisor-api/src/v2/api/controllers/ScheduleController.ts, fictadvisor-api/src/v2/api/dtos/UpdateEventDTO.ts, fictadvisor-api/src/v2/api/responses/EventInfoResponse.ts, fictadvisor-api/src/v2/api/responses/EventResponse.ts, fictadvisor-api/src/v2/api/services/ScheduleService.ts, fictadvisor-api/src/v2/mappers/ScheduleMapper.ts
- added ability to work with telegram
- created endpoint for getting info about event
- updated swagger documentation
closes #151
=> feature #151: saved homework in pairs

fictadvisor-api/src/v2/api/controllers/ScheduleController.ts, fictadvisor-api/src/v2/api/services/ScheduleService.ts
=> bugfix #204: fixed bugs in new schedule logic

fictadvisor-web/src/app/schedule/page.tsx
- added force dynamic 
closes #216
=> fix #216: removed semester caching on schedule page

fictadvisor-web/src/components/pages/schedule-page/SchedulePage.tsx, fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule-header/ScheduleHeader.tsx
- display loading skeletons only on event fetching
closes #218
=> 💅 #218:displaying loading skeletons only on loading

fictadvisor-web/src/store/schedule/useSchedule.ts
- changed timezone from +02:00 to +03:00
closes #221
=> bugfix #221: change timezone on schedule

fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx, fictadvisor-web/src/components/pages/search-pages/teacher-search/components/TeacherSearchList.tsx
- fixed display button 'download more'
closes #210
=> bug #210: fixed 'download more' button

fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/editing-column/EditingColumn.styles.ts
=> bug #148: align group students

fictadvisor-web/src/components/common/layout/header/components/mobile-header/components/drawer/Drawer.tsx
- added params in the pathname handling
closes #231
=> bug #231: highlight current tab

fictadvisor-api/src/v2/utils/parser/RozParser.ts
- now teachers creating correctly
closes #229
- description 1
- description 2
closes #issue_number
=> bugfix #229: fixed roz kpi parser

fictadvisor-api/src/v2/api/dtos/SortQAQParam.ts
- added sorting by question category on /poll/questions
closes #235
=> enhancement #235: improved get all questions endpoint

fictadvisor-web/src/components/pages/schedule-page/SchedulePage.tsx
- fixed events load requests dublicated
closes #228
=> bug #228: fix bug events load requests dublicate

fictadvisor-web/src/components/pages/register/register-page/components/register-form/RegisterForm.tsx
- removed max length parameter for password from register form
closes #196
=> bug #196: unified validation reaction

fictadvisor-web/src/components/pages/password-recovery/create-password-page/components/create-password-form/CreatePasswordForm.tsx
- changed placeholders in password recovery form
closes #206
=> bugfix #206: changed placeholders in password recovery form

fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx
- changed the returning page value in function
closes #193
=> bug #193: fixed teachers fetching second request

fictadvisor-api/src/v2/api/services/GroupService.ts
- added new grants with set false
closes #213
=> bugfix #213: fixed permissions for default students

fictadvisor-web/src/components/common/layout/header/components/mobile-header/components/drawer/Drawer.styles.ts, fictadvisor-web/src/components/common/layout/page-layout/PageLayout.module.scss
- Changed zIndex from 2 to 11 in drawer
- Changed zIndex from 10 to 12 in header
closes #33
=> bug #33: fixed button and event form overlaying over drawer

fictadvisor-web/src/app/account/page.tsx, fictadvisor-web/src/app/page.tsx, fictadvisor-web/src/app/schedule/page.tsx
=> bug #242: fixed titles on home, schedule, account pages

fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts, fictadvisor-api/src/v2/api/services/UserService.ispec.ts, fictadvisor-api/src/v2/api/services/UserService.ts, fictadvisor-api/src/v2/modules/UserModule.ts
- modified changeGroup method in UserService to add teachers of new group from previous semesters to RemovedDisciplineTeachers table in db
- added TeacherModule, PollModule to imports in  UserModule
closes #177
=> feature #177: restricted access to the teachers in poll

fictadvisor-web/src/components/pages/admin/admin-comments/components/admin-comments-table/CommentsTable.tsx
- changed thead to TableHead
closes #253
=> enhancement #253: fix admin answers review

fictadvisor-web/src/components/pages/account-page/components/selective-tab/components/opened-selective/OpenedSelective.tsx, fictadvisor-web/src/components/pages/account-page/components/selective-tab/components/selective-block/SelectiveBlock.tsx
=> bug #209: fixed year display in selective subjects

fictadvisor-web/src/components/common/ui/form/input-mui/Input.styles.ts, fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/ScheduleEventForm.tsx
- Fixed input placeholder styles
closes #249
=> bug #249: inputs placeholders text in user create admin tab

fictadvisor-web/src/components/common/layout/admin-panel/constants/index.tsx
=> bug #89: fixed admin panel links

fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule/Schedule.styles.ts, fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule/components/schedule-time/ScheduleTime.tsx
- add additional row with time for proper displaying events after 11 p.m.
closes #150
=> bug #150: fix bug with event beyond schedule

fictadvisor-web/src/components/common/ui/button-mui/Button.styles.ts
- changed border radius in ui kit button-mui
closes #269
=> enhancement #269: change border radius in ui kit button-mui

fictadvisor-web/src/app/admin/disciplines/create/page.tsx, fictadvisor-web/src/app/admin/disciplines/edit/[disciplineId]/page.tsx, fictadvisor-web/src/app/admin/disciplines/page.tsx, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/DisciplinesAdminPage.styles.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/DisciplinesAdminPage.tsx, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-admin-search/DisciplinesAdminSearch.styles.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-admin-search/DisciplinesAdminSearch.tsx, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-admin-search/constants/index.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-admin-search/index.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-admin-search/types/index.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-table/DisciplinesTable.styles.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-table/DisciplinesTable.tsx, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-table/index.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/index.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-create-page/DisciplinesAdminCreatePage.styles.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-create-page/DisciplinesAdminCreatePage.tsx, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-create-page/index.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/DisciplinesAdminEditPage.tsx, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/DisciplinesAdminPage.styles.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/components/disciplines-info-section/DisciplinesInfoSection.styles.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/components/disciplines-info-section/DisciplinesInfoSection.tsx, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/components/disciplines-info-section/index.ts, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/index.ts, fictadvisor-web/src/lib/api/discipline/DisciplineAPI.ts, fictadvisor-web/src/lib/api/discipline/types/AddDiscipline.ts, fictadvisor-web/src/lib/api/discipline/types/AddDisciplineTeacher.ts, fictadvisor-web/src/lib/api/discipline/types/GetAllDisciplineTeachers.ts, fictadvisor-web/src/lib/api/discipline/types/GetAllDisciplines.ts, fictadvisor-web/src/lib/api/discipline/types/UpdateDisciplineTeacher.ts, fictadvisor-web/src/types/discipline.ts
=> feature #36: created a discipline flow

fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/TeacherPersonalInputs.styles.ts, fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/TeacherPersonalInputs.tsx, fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/ChangeAvatar.styles.ts, fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/ChangeAvatar.tsx, fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/components/avatar-dropzone/AvatarDropzone.styles.ts, fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/components/avatar-dropzone/AvatarDropzone.tsx, fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/components/avatar-dropzone/index.ts, fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/components/avatar-dropzone/utils/handleFileSelect.ts, fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/index.ts, fictadvisor-web/src/components/pages/admin/admin-teachers/create-teacher-admin-page/components/header-create/HeaderCreate.tsx, fictadvisor-web/src/components/pages/admin/admin-teachers/create-teacher-admin-page/types/index.ts, fictadvisor-web/src/components/pages/admin/admin-teachers/edit-teachers-admin-page/TeachersAdminEditPage.tsx, fictadvisor-web/src/components/pages/admin/admin-teachers/edit-teachers-admin-page/components/edit-teacher-comments/components/comment-text-area/CommentTextArea.styles.ts, fictadvisor-web/src/components/pages/admin/admin-teachers/edit-teachers-admin-page/components/header-edit/HeaderEdit.tsx
- added edit teacher`s photo
- added create teacher`s photo
- fix error 404 on the admin panel teacher creation page after clicking the "Скасувати" button
- fix error 404 on the admin panel teacher editing page after clicking the "Скасувати" button
- fix that the field with comments is located in the center on the "Edit teacher" page
closes: #271
=> bugfix #271: fixed bugs on teacher admin page

fictadvisor-web/src/components/pages/schedule-page/SchedulePage.tsx, fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/validation/index.ts
- added validation on teachers field
closes #24
=> bug #24: null value teacher is accepted

fictadvisor-api/email/templates/template.hbs, fictadvisor-api/src/v2/api/services/AuthService.ts
=> feature #75: added html to mail messages

fictadvisor-api/prisma/migrations/20240319162757_rename_icon_colum_for_student_resource/migration.sql, fictadvisor-api/prisma/schema.prisma, fictadvisor-api/src/v2/api/datas/CreateResourceData.ts, fictadvisor-api/src/v2/api/datas/UpdateResourceData.ts, fictadvisor-api/src/v2/api/dtos/CreateResourceDTO.ts, fictadvisor-api/src/v2/database/repositories/ResourceRepository.ts
- renamed icon colum to imageLink
closes #294
=> migration #294 Rename icon column on resource table

fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/ScheduleEventForm.tsx, fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/constants/index.ts, fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/validation/index.ts, fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
- added event type checking on schedule card
- removed teacher validation on "other event" type
closes #23
=> bug #23: other event fields are not visible

fictadvisor-web/src/app/manifest.ts
- added manifest.json
- added service worker
closes #8
=> feature #8: added manifest.json

fictadvisor-api/src/v2/modules/AccessModule.ts, fictadvisor-api/src/v2/security/multiple-access-guard/MultipleAccessGuard.ts, fictadvisor-api/src/v2/utils/documentation/decorators.ts
- fixed a bug with poll page not displaying
closes #308
=> bug #308: fixed multiple access guard

fictadvisor-api/src/v2/api/controllers/StudentController.ts, fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx, fictadvisor-web/src/components/pages/admin/admin-comments/CommentsAdminPage.tsx, fictadvisor-web/src/components/pages/admin/admin-comments/components/admin-comments-table/CommentsTable.tsx, fictadvisor-web/src/components/pages/admin/admin-departments/admin-departments-search-page/AdminDepartmentSearchPage.tsx, fictadvisor-web/src/components/pages/admin/admin-departments/admin-departments-search-page/components/admin-departments-table/AdminDepartmentsTable.tsx, fictadvisor-web/src/components/pages/admin/admin-groups/create-groups-admin-page/AdminGroupsCreate.tsx, fictadvisor-web/src/components/pages/admin/admin-groups/create-groups-admin-page/components/header-create/HeaderCreate.tsx, fictadvisor-web/src/components/pages/admin/admin-groups/edit-groups-admin-page/components/header-edit/HeaderEdit.tsx, fictadvisor-web/src/components/pages/admin/admin-groups/search-groups-admin-page/AdminGroupsPage.tsx, fictadvisor-web/src/components/pages/admin/admin-groups/search-groups-admin-page/components/groups-table/GroupsTable.tsx, fictadvisor-web/src/components/pages/admin/admin-student/create-student-page/AdminStudentCreate.styles.ts, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/AdminSubjectSearchPage.tsx, fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-table/AdminSubjectTable.tsx, fictadvisor-web/src/components/pages/admin/admin-teachers/search-teacher-admin-page/components/teachers-table/TeachersTable.tsx, fictadvisor-web/src/components/pages/admin/admin-user/search-user-page/components/users-list/UsersList.tsx, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/DisciplinesAdminPage.tsx, fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-table/DisciplinesTable.tsx, fictadvisor-web/src/components/pages/admin/questions-admin-page/QueationsAdminPage.tsx, fictadvisor-web/src/components/pages/admin/questions-admin-page/components/questions-edit-page/QuestionsEditPage.tsx, fictadvisor-web/src/components/pages/admin/questions-admin-page/components/questions-search-page/components/questions-table/QuestionsTable.tsx, fictadvisor-web/src/components/pages/search-pages/subject-search/components/SubjectSearchList.tsx, fictadvisor-web/src/lib/api/subject/types/GetListOfSubjectsResponse.ts, fictadvisor-web/src/lib/api/teacher/types/GetCommentsWithPaginationResponse.ts, utils/src/security/PERMISSION.ts
- fixed bugs on admin student page
- fixed bugs on admin groups page
- remove key={index} in all tables in admin
closes #310, closes #311, closes #312, closes #313
=> bug #310: fixed bugs on admin pages

fictadvisor-web/src/store/schedule/useSchedule.ts
=> bugfix #59: made schedule check state of request

fictadvisor-api/src/v2/api/controllers/UserController.ts, fictadvisor-api/src/v2/api/services/UserService.ts, fictadvisor-web/src/components/pages/admin/admin-user/edit-user-page/EditUserPage.tsx, fictadvisor-web/src/components/pages/schedule-page/calendar-section/CalendarSection.tsx, fictadvisor-web/src/lib/api/user/UserAPI.ts, fictadvisor-web/src/types/user.ts
- changed user controller to return user, not student
- remove group checking on schedule
- added new type of user (without student info)
closes #251, closes #250
=> bugfix #251, #250: fixed editing not verified user on admin panel

fictadvisor-api/src/v2/api/services/AuthService.ts
- added check that will lead to forgot password algorithm
closes #298
=> bugfix #298: fixed error with required arguments

fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
- added telegram guard on PATCH /v2/schedule/groups/{groupId}/events/{eventId} endpoint
closes #338
=> enhancement #338: added telegram guard

fictadvisor-web/public/service-worker.js, fictadvisor-web/src/app/layout.tsx
- initialized service worker
- added service-worker.js
closes #2
=> feature #2: added service worker

fictadvisor-api/src/v2/api/controllers/CathedraController.ts, fictadvisor-api/src/v2/api/responses/DisciplineTeachersResponse.ts, fictadvisor-api/src/v2/mappers/DisciplineMapper.ts
- added group field to DisciplineTeachersResponse
- fixed bug with cathedra divisions
- swagger documentation for discipline and cathedra was already solved
closes #349
=> bugfix #349: Fixed discipline and cathedra endpoints

fictadvisor-web/public/service-worker.js, fictadvisor-web/src/app/layout.tsx
- initialized service worker
- added service-worker.js
- added fetching data from API
- fixed auth
closes #2
=> feature #2: fixed service worker

fictadvisor-api/src/v2/api/controllers/TeacherController.ts
- updated delete endpoint
- updated getAllContacts endpoint
- updated getContact endpoint
- updated createContact endpoint
- updated updateContac endpoint
- updated deleteContact endpoint
closes #252
=> documentation #252: updated swagger for teachers 

fictadvisor-api/src/v2/api/controllers/PageTextController.ts, utils/src/security/PERMISSION.ts
- removed permission from  get pagetext endpoint
closes #376
=> bugfix #376: get pagetext needs permission

fictadvisor-web/public/service-worker.js, fictadvisor-web/src/app/layout.tsx
- fixed sw
- added checking on production
closes #380
=> enhancement #380: make sw for production

fictadvisor-web/src/app/main-page/MainPage.styles.ts, fictadvisor-web/src/app/main-page/constants/MainPageConstants.ts, fictadvisor-web/src/app/not-found.tsx, fictadvisor-web/src/app/page.tsx, fictadvisor-web/src/lib/metadata/not-found.ts
- changed data fetching format
- changed styles
- added buttons
closes #316, closes #141
=> enhancement #316: rewrote main page to the server component

fictadvisor-web/src/app/(search-pages)/search-form/SearchForm.tsx, fictadvisor-web/src/app/(search-pages)/teachers/components/TeacherSearchList.tsx, fictadvisor-web/src/app/(search-pages)/teachers/page.tsx
- removed ability to clean up the sort field
- fixed toast error
closes #363
=> bug #363: the teacher page is not displayed

fictadvisor-web/src/app/layout.tsx, fictadvisor-web/src/app/page.tsx, fictadvisor-web/src/components/common/layout/providers/Providers.tsx, fictadvisor-web/src/components/common/layout/providers/index.ts
- created component Providers and move all providers there
- added generation metadata base path url
closes #387
=> bug #387: fixed wrong OG image url

fictadvisor-web/src/components/common/layout/footer/constants/index.tsx
- fixed missing brand name on the website to FICE
closes #291
=> bug #291 fixed missing brand name on the website to FICE

fictadvisor-web/src/app/layout.tsx, fictadvisor-web/src/app/page.tsx
- migrated layout.tsx to new architecture
- deleted extra fonts link
closes #322
=> enhancement #322: improved layout.tsx

fictadvisor-web/src/app/admin/disciplines/search/constants/index.ts, fictadvisor-web/src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.styles.ts, fictadvisor-web/src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.tsx, fictadvisor-web/src/types/teacher.ts
=> feature #254: added new teacher card fields

fictadvisor-api/src/v2/api/controllers/UserController.ts, utils/src/requests/SelectiveDisciplinesDTO.ts
- changed UserByIdPipe to StudentByIdPipe in attachSelectiveDisciplines endpoint of UserController
- added validation for discipline ids array
closes #300
=> bug #300: fixed attachSelectiveDisciplines endpoint

fictadvisor-api/package.json, fictadvisor-api/src/v2/api/services/ScheduleService.ts, fictadvisor-api/src/v2/utils/date/DateService.spec.ts, fictadvisor-api/src/v2/utils/date/DateService.ts
- added luxon to the project
- changed setWeekTime in ScheduleService
- simplified methods in DateService
closes #333
=> enhancement #333: added datetime library

fictadvisor-web/src/app/(main)/error-pages/MainErrorPage.styles.ts, fictadvisor-web/src/app/error.tsx
- created error.tsx file for pages and layouts errors handling
- wrote a temporary design for them
closes #337
=> feature #337: implemented an error page for all routes

fictadvisor-api/src/v2/api/services/ScheduleService.ts
- fixed some bugs in update event endpoint
closes #296
=> bug #296: fixed bugs in update event endpoint

fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts, utils/src/security/PERMISSION.ts
- Changed permissions in getQuestions and sendAnswers endpoints
=> Fixed bug on poll

fictadvisor-api/src/v2/api/controllers/ScheduleController.ts, fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts, fictadvisor-api/src/v2/api/services/ScheduleService.ts, utils/src/requests/UpdateEventDTO.ts
- created integration tests for updateEvent method of ScheduleService
- added check for changing end date in service method
- added `changeEndDate` property to UpdateEventDTO
closes #62
=> enhancement #62: implemented integration tests for updateEvent method

fictadvisor-web/src/app/admin/students/edit/[studentId]/page.tsx
previously it was throwing an error before loading checks, i rearranged some if statements and now it seems to work right
closes #336
=> bug #336: rearranged some if statements to make right logic

.gitignore, fictadvisor-web/src/app/(main)/(search-pages)/poll/[disciplineTeacherId]/layout.tsx
- fixed doubled footer on survey page
closes #402
=> bug #402 fixed doubled footer on survey page

fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts, fictadvisor-api/src/v2/utils/documentation/decorators.ts, utils/src/security/PERMISSION.ts
- rollbacked poll permissions
closes #417
=> bug #417: rollbacked poll permissions

fictadvisor-web/src/app/(main)/schedule/schedule-page/schedule-section/components/schedule/components/schedule-line/ScheduleLine.tsx, fictadvisor-web/src/store/schedule/useSchedule.ts
- fixed incorrect time display after hovering over ScheduleLine after visiting other pages
closes #362
=> bug #362 fixed time in the time bar on the "Schedule" page

fictadvisor-web/src/hooks/use-authentication/authentication-context/AuthenticationContext.tsx, fictadvisor-web/src/lib/api/auth/AuthAPI.ts
=> fix next`s auth context

fictadvisor-api/src/v2/api/services/EmailService.ts
=> bug #427: fixed bug in email service

.github/workflows/deploy-back.yml
changed Start PostgreSQL Database command from `docker-compose` to `docker compose`
=> fix deploy-back command name

fictadvisor-api/.gitignore, fictadvisor-api/package.json, fictadvisor-api/src/v2/api/services/DocumentService.ts, fictadvisor-api/src/v2/api/services/GroupService.ts, fictadvisor-api/src/v2/api/services/UserService.ts, fictadvisor-api/src/v2/modules/GroupModule.ts, fictadvisor-api/src/v2/utils/files/FileService.ts
- replaced local storing of files with Firebase Storage
closes #468
=> refactor #468: rewritten file manager

fictadvisor-api/src/v2/api/services/UserService.ts, utils/src/requests/EmailDTO.ts
- fixed emails validation
- fixed avatar update
=> bug: fixed bugs

fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/groups-dropdown/GroupsDropDown.tsx, fictadvisor-web/src/components/common/ui/form/dropdown/Dropdown.tsx
=> bug #473 fixed field for entering the group name and dropdown menu

fictadvisor-web/src/components/common/ui/cards/poll-teacher-card/pollTeachaerCard.styles.ts
- fixed cross highlighting
closes #406
=> bug #406: fixed cross highlighting on the 'Survey' page

fictadvisor-web/package.json, fictadvisor-web/src/components/common/layout/providers/Providers.tsx, yarn.lock
=> enhancement #485: React Query Devtools

fictadvisor-api/src/v2/api/services/UserService.ts, fictadvisor-api/src/v2/utils/files/FileService.ts
- fixed verifyStudent functions
closes #467
=> bug #467: fixed verifyStudent functions

fictadvisor-api/src/v2/api/services/UserService.ts
- removed sending messages to telegram bot when selective disciplines are missed and user is verified
=> bug: removed sending telegram messages

fictadvisor-api/src/v2/api/controllers/DisciplineController.ts, fictadvisor-api/src/v2/api/services/DisciplineService.ts, utils/src/requests/UpdateDisciplineDTO.ts, utils/src/security/PERMISSION.ts
- Added endpoint to update discipline
=> feature: added endpoint to update discipline

fictadvisor-api/src/v2/api/services/GroupService.ts
- Fixed bug on removeStudent endpoint
=> bug: fixed removing student from group

fictadvisor-api/src/v2/api/controllers/AuthController.ts, fictadvisor-api/src/v2/api/controllers/StudentController.ts, fictadvisor-api/src/v2/api/pipes/StudentByIdPipe.ts, fictadvisor-api/src/v2/database/repositories/StudentRepository.ts, fictadvisor-api/src/v2/mappers/StudentMapper.ts, fictadvisor-api/src/v2/utils/documentation/student/createStudent.ts, fictadvisor-api/src/v2/utils/documentation/student/deleteStudent.ts, fictadvisor-api/src/v2/utils/documentation/student/getAll.ts, fictadvisor-api/src/v2/utils/documentation/student/getRemainingSelectives.ts, fictadvisor-api/src/v2/utils/documentation/student/getSelectiveDisciplines.ts, fictadvisor-api/src/v2/utils/documentation/student/getStudent.ts, fictadvisor-api/src/v2/utils/documentation/student/index.ts, fictadvisor-api/src/v2/utils/documentation/student/updateStudent.ts, fictadvisor-api/src/v2/utils/documentation/student/updateStudentSelectives.ts, utils/src/requests/CreateStudentDTO.ts, utils/src/requests/StudentDTO.ts, utils/src/requests/StudentOfGroupDTO.ts
- Separated documentation of endpoints in student controller
- Refactored related DTOs
closes #503
=> enhancement #503: refactored Student entity

fictadvisor-api/package.json, fictadvisor-api/src/v2/api/ApiModule.ts, fictadvisor-api/src/v2/api/controllers/HealthController.ts, fictadvisor-api/src/v2/modules/HealthModule.ts, yarn.lock
=> feature: added healthcheck endpoint

fictadvisor-api/src/v2/api/controllers/AuthController.ts, fictadvisor-api/src/v2/utils/documentation/auth/checkCaptain.ts, fictadvisor-api/src/v2/utils/documentation/auth/checkRegisterTelegram.ts, fictadvisor-api/src/v2/utils/documentation/auth/checkResetToken.ts, fictadvisor-api/src/v2/utils/documentation/auth/forgotPassword.ts, fictadvisor-api/src/v2/utils/documentation/auth/getMe.ts, fictadvisor-api/src/v2/utils/documentation/auth/index.ts, fictadvisor-api/src/v2/utils/documentation/auth/login.ts, fictadvisor-api/src/v2/utils/documentation/auth/loginTelegram.ts, fictadvisor-api/src/v2/utils/documentation/auth/refresh.ts, fictadvisor-api/src/v2/utils/documentation/auth/register.ts, fictadvisor-api/src/v2/utils/documentation/auth/registerTelegram.ts, fictadvisor-api/src/v2/utils/documentation/auth/requestEmailVerification.ts, fictadvisor-api/src/v2/utils/documentation/auth/resetPassword.ts, fictadvisor-api/src/v2/utils/documentation/auth/updatePassword.ts, fictadvisor-api/src/v2/utils/documentation/auth/verifyEmail.ts, fictadvisor-api/src/v2/utils/documentation/auth/verifyExistsByUnique.ts, fictadvisor-api/src/v2/utils/documentation/decorators.ts, utils/src/requests/ForgotPasswordDTO.ts, utils/src/requests/IdentityQueryDTO.ts, utils/src/requests/LoginDTO.ts, utils/src/requests/RegisterTelegramDTO.ts, utils/src/requests/ResetPasswordDTO.ts, utils/src/requests/StudentDTO.ts, utils/src/requests/UserDTO.ts, utils/src/requests/VerificationEmailDTO.ts
- added tooManyRequests property to ApiDocumentationParams
- moved documentation to separate files
- added missing validation decorators to some DTOs
- removed promise return types from controller methods
closes #513
=> enhancement #513: refactored auth controller

fictadvisor-api/src/v2/api/controllers/CathedraController.ts, fictadvisor-api/src/v2/utils/documentation/cathedra/create.ts, fictadvisor-api/src/v2/utils/documentation/cathedra/delete.ts, fictadvisor-api/src/v2/utils/documentation/cathedra/getAll.ts, fictadvisor-api/src/v2/utils/documentation/cathedra/getAllDivisions.ts, fictadvisor-api/src/v2/utils/documentation/cathedra/getById.ts, fictadvisor-api/src/v2/utils/documentation/cathedra/index.ts, fictadvisor-api/src/v2/utils/documentation/cathedra/update.ts, utils/src/requests/CreateCathedraDTO.ts, utils/src/requests/QueryAllCathedrasDTO.ts, utils/src/requests/UpdateCathedraDTO.ts
- moved documentation to separate files
- added missing validation decorators to some DTOs
- removed promise return types from controller methods
closes #512
=> enhancement #512: refactored cathedra controller

fictadvisor-api/src/v2/api/controllers/TeacherController.ts, fictadvisor-api/src/v2/api/services/TeacherService.spec.ts, fictadvisor-api/src/v2/api/services/TeacherService.ts, fictadvisor-api/src/v2/mappers/TeacherMapper.ts
- refactored teacher service and test for it
closes #501
=> enhancment #501 refactoring teacher controller and service

fictadvisor-api/src/v2/api/controllers/AuthController.ts, fictadvisor-api/src/v2/telegram/TelegramAPI.ts, fictadvisor-api/src/v2/utils/documentation/auth/login.ts, fictadvisor-api/src/v2/utils/documentation/decorators.ts, utils/src/requests/RemainingSelectivesDTO.ts, utils/src/requests/StudentDTO.ts, utils/src/requests/UserDTO.ts
- fixed discipline selecting
- added api body for login endpoint
- fixed registration error
- found and fixed axios exception bug
closes #542
=> bug #542: fixed small bugs

fictadvisor-api/.eslintrc.cjs, fictadvisor-api/src/v2/api/services/UserService.ts, fictadvisor-api/src/v2/utils/documentation/user/requestNewGroup.ts, fictadvisor-api/src/v2/utils/exceptions/AlreadySentGroupRequestException.ts
- added check for PENDING status of the group join request
- created custom exception for this
closes #399
=> bug #399: fixed spam to group captain

fictadvisor-web/src/app/(main)/(search-pages)/search-form/SearchForm.tsx, fictadvisor-web/src/app/(main)/(search-pages)/teachers/page.tsx
- fixed bug with error message appearing on every reload of "Викладачі" page
closes #540
=> bug #540: fixed error message showing on reloading the page

fictadvisor-api/src/v2/api/controllers/PageTextController.ts, fictadvisor-api/src/v2/api/pipes/PageTextByKeyPipe.ts, fictadvisor-api/src/v2/api/pipes/ValidatePageTextsPipe.ts, fictadvisor-api/src/v2/api/services/PageTextService.ts, fictadvisor-api/src/v2/utils/documentation/pageText/create.ts, fictadvisor-api/src/v2/utils/documentation/pageText/getAll.ts, fictadvisor-api/src/v2/utils/documentation/pageText/index.ts, fictadvisor-api/src/v2/utils/documentation/pageText/updateMany.ts, utils/src/requests/CreatePageTextDTO.ts, utils/src/requests/CreateQuestionRoleDTO.ts, utils/src/requests/QueryAllPageTextsDTO.ts, utils/src/requests/UpdatePageTextsDTO.ts
- Separated documentation of endpoints in PageText controller
- Refactored related DTOs
- Created PageTextByKeyPipe
- Created ValidatePageTextsPipe
closes #509
=> enhancement #509: refactored PageText controller

fictadvisor-api/src/v2/api/services/AuthService.ts, fictadvisor-api/src/v2/api/services/GroupService.ts, fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts, fictadvisor-api/src/v2/api/services/ScheduleService.spec.ts, fictadvisor-api/src/v2/api/services/StudentService.ts, fictadvisor-api/src/v2/api/services/UserService.ts, fictadvisor-api/src/v2/database/repositories/GroupRepository.ts, fictadvisor-api/src/v2/security/JwtStrategy.ts, fictadvisor-api/src/v2/utils/date/DateService.ts, fictadvisor-api/src/v2/utils/parser/CampusParser.ts, fictadvisor-api/src/v2/utils/parser/ParserModule.ts, fictadvisor-api/src/v2/utils/parser/RozParser.ts
- found and fixed bug with invalid date
- added creating of group roles in campus parser
closes #549
=> bug #549: fixed groups creating by parser

fictadvisor-api/src/v2/api/controllers/DateController.ts, fictadvisor-api/src/v2/api/pipes/ConvertToBooleanPipe.ts, fictadvisor-api/src/v2/api/services/PollService.ts, fictadvisor-api/src/v2/utils/date/DateService.ts, fictadvisor-api/src/v2/utils/documentation/date/getCurrentSemester.ts, fictadvisor-api/src/v2/utils/documentation/date/getPreviousSemesters.ts, fictadvisor-api/src/v2/utils/documentation/date/index.ts
-  separated documentation of endpoints in date controller
closes #545
=> enhancement #545: refactored date controller

fictadvisor-web/src/lib/services/group/GroupService.ts
- fixed buttons absence on group tab
- added missing permission checks
closes #544
=> bug #544: fixed buttons absence on group tab

fictadvisor-api/src/v2/api/controllers/ResourceController.ts, fictadvisor-api/src/v2/api/pipes/ValidateResourcesPipe.ts, fictadvisor-api/src/v2/api/services/ResourceService.ts, fictadvisor-api/src/v2/mappers/ResourceMapper.ts, fictadvisor-api/src/v2/utils/documentation/resource/create.ts, fictadvisor-api/src/v2/utils/documentation/resource/delete.ts, fictadvisor-api/src/v2/utils/documentation/resource/get.ts, fictadvisor-api/src/v2/utils/documentation/resource/getAll.ts, fictadvisor-api/src/v2/utils/documentation/resource/index.ts, fictadvisor-api/src/v2/utils/documentation/resource/update.ts, fictadvisor-api/src/v2/utils/documentation/resource/updateMany.ts, fictadvisor-web/src/app/admin/main/components/student-resources-form/StudentResourcesForm.tsx, fictadvisor-web/src/app/page.tsx, fictadvisor-web/src/lib/api/student-resources/StudentResourcesAPI.ts, utils/src/requests/CreateResourceDTO.ts, utils/src/requests/QueryAllResourcesDTO.ts, utils/src/requests/UpdateResourceDTO.ts, utils/src/requests/UpdateResourcesDTO.ts, utils/src/responses/ResourcesResponse.ts
- Refactor swagger documentation in controller
- Create new pipe for validation
- Refactor some methods in service
- Enhance validation in DTOs
closes #506
=> enhancement #506: refactored Resource entity

fictadvisor-api/src/v2/api/controllers/TelegramGroupController.ts, fictadvisor-api/src/v2/api/services/TelegramGroupService.ts, fictadvisor-api/src/v2/mappers/TelegramGroupMapper.ts, fictadvisor-api/src/v2/utils/documentation/telegramGroup/create.ts, fictadvisor-api/src/v2/utils/documentation/telegramGroup/delete.ts, fictadvisor-api/src/v2/utils/documentation/telegramGroup/getAll.ts, fictadvisor-api/src/v2/utils/documentation/telegramGroup/getById.ts, fictadvisor-api/src/v2/utils/documentation/telegramGroup/index.ts, fictadvisor-api/src/v2/utils/documentation/telegramGroup/update.ts, utils/src/requests/CreateTelegramGroupDTO.ts, utils/src/requests/UpdateTelegramGroupDTO.ts
refactoring telegramGroup controller
closes #500
=> enhancment #500 refactoring telegramGroup controller

fictadvisor-api/src/v2/api/controllers/DisciplineController.ts, fictadvisor-api/src/v2/api/controllers/GroupController.ts, fictadvisor-api/src/v2/api/services/DisciplineService.ts, fictadvisor-api/src/v2/mappers/DisciplineMapper.ts, fictadvisor-api/src/v2/utils/documentation/discipline/create.ts, fictadvisor-api/src/v2/utils/documentation/discipline/deleteById.ts, fictadvisor-api/src/v2/utils/documentation/discipline/getAll.ts, fictadvisor-api/src/v2/utils/documentation/discipline/getAllTeachersByDiscipline.ts, fictadvisor-api/src/v2/utils/documentation/discipline/getById.ts, fictadvisor-api/src/v2/utils/documentation/discipline/index.ts, fictadvisor-api/src/v2/utils/documentation/discipline/updateById.ts, utils/src/requests/CreateDisciplineDTO.ts, utils/src/requests/QueryAllDisciplinesDTO.ts, utils/src/requests/QuerySemesterDTO.ts, utils/src/responses/DisciplineResponse.ts
- Change some methods names in service
- Change some methods names in comtroller
- Refactor swagger documentation in controller 
- Add more validation to DTO's
- Add documentation to DTO's
closes #511
=> enhancement #511: Refactor Discipline entity

fictadvisor-api/src/v2/api/controllers/SubjectController.ts, fictadvisor-api/src/v2/api/pipes/AllSubjectsPipe.ts, fictadvisor-api/src/v2/api/services/SubjectService.ts, fictadvisor-api/src/v2/modules/SubjectModule.ts, fictadvisor-api/src/v2/utils/documentation/subject/create.ts, fictadvisor-api/src/v2/utils/documentation/subject/delete.ts, fictadvisor-api/src/v2/utils/documentation/subject/get.ts, fictadvisor-api/src/v2/utils/documentation/subject/getAll.ts, fictadvisor-api/src/v2/utils/documentation/subject/getTeachers.ts, fictadvisor-api/src/v2/utils/documentation/subject/index.ts, fictadvisor-api/src/v2/utils/documentation/subject/update.ts, utils/src/requests/CreateSubjectDTO.ts, utils/src/requests/QueryAllSubjectDTO.ts, utils/src/requests/UpdateSubjectDTO.ts
- created documentation files for each SubjectController endpoint
- refactored CreateSubjectDTO, QueryAllSubjectDTO, UpdateSubjectDTO
closes #502
=> enhancement #502: refatored Subject entity

fictadvisor-web/src/lib/api/group/GroupAPI.ts, fictadvisor-web/src/lib/services/group/GroupService.ts
- Fixed the bug where the "Sort Group" button wasn't working.
closes #563
=> Bug #563: fixed button sort group

fictadvisor-web/.env.development, fictadvisor-web/src/app/(main)/(search-pages)/teachers/page.tsx
- fixed incorrect display of teacher list when press on button "Завантажити ще"
closes #570
=> bug #570: fix teacher list display

fictadvisor-web/src/components/common/ui/load-page/LoadPage.tsx
- description 1
- description 2
closes #issue_number
=> fix: load offset

fictadvisor-web/.env.development, fictadvisor-web/src/app/(main)/(search-pages)/teachers/page.tsx, fictadvisor-web/src/components/common/ui/cards/card-discipline-types/CardDisciplineTypes.module.scss, fictadvisor-web/src/components/common/ui/cards/card-discipline-types/CardDisciplineTypes.tsx
- Fixed the display issue with discipline type icons
closes #571
=> bug #571: fixed displaying of discipline type icons

fictadvisor-api/src/v2/api/controllers/ScheduleController.ts, fictadvisor-api/src/v2/api/pipes/ScheduleTimeConvertPipe.ts, fictadvisor-api/src/v2/api/services/ScheduleService.ts, fictadvisor-api/src/v2/modules/ScheduleModule.ts
- added correct time setting on update
closes #539
=> bug #539: fixed incorrect time after event editing

fictadvisor-api/src/v2/api/controllers/PollController.ts, fictadvisor-api/src/v2/api/pipes/QuestionByRoleAndIdPipe.ts, fictadvisor-api/src/v2/api/services/PollService.ts, fictadvisor-api/src/v2/database/repositories/QuestionRepository.ts, fictadvisor-api/src/v2/mappers/QuestionMapper.ts, fictadvisor-api/src/v2/utils/documentation/poll/create.ts, fictadvisor-api/src/v2/utils/documentation/poll/delete.ts, fictadvisor-api/src/v2/utils/documentation/poll/deleteRole.ts, fictadvisor-api/src/v2/utils/documentation/poll/getAll.ts, fictadvisor-api/src/v2/utils/documentation/poll/getPollDisciplineTeachers.ts, fictadvisor-api/src/v2/utils/documentation/poll/getQuestion.ts, fictadvisor-api/src/v2/utils/documentation/poll/giveRole.ts, fictadvisor-api/src/v2/utils/documentation/poll/index.ts, fictadvisor-api/src/v2/utils/documentation/poll/update.ts, utils/src/requests/CreateQuestionDTO.ts, utils/src/requests/CreateQuestionRoleDTO.ts, utils/src/requests/UpdateQuestionDTO.ts
- Add return types to service, mapper and repos
- Change some methods visibility to private
- Add some documentation to DTO's
- Move swagger documentation from controller to separate object
closes #507
=> enhancement #507: Refactor Poll controller

fictadvisor-api/src/v2/api/services/PollService.ts
- added to poll list only disciplines from finished semesters
closes #587
=> bug #587: fixed polls displaying

fictadvisor-web/src/app/(main)/(search-pages)/search-form/SearchForm.tsx, fictadvisor-web/src/app/(main)/(search-pages)/search-form/constants.ts, fictadvisor-web/src/app/(main)/(search-pages)/search-form/types/index.ts, utils/src/requests/QueryAllTeacherDTO.ts
- removed empty groupId strings from request queries
- added uuid validation for teachers
closes #586
=> bug #586: fixed subject displaying

fictadvisor-web/src/app/(main)/(search-pages)/poll/PollTeacherPage.styles.ts, fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/date-picker/DatePicker.tsx, fictadvisor-web/src/styles/typography.scss
-Fixed font styling issues.
-Changed the language of the calendar to Ukrainian.
-Corrected padding on the poll page.
closes #590
=> bug #590: fixed design inconsistencies

fictadvisor-api/package.json, fictadvisor-api/src/v2/utils/files/FileService.ts, yarn.lock
- changed generation of group list from csv to xlsx format
=> enhancement: added group list generation in xlsx format

fictadvisor-api/src/v2/api/controllers/ScheduleController.ts, fictadvisor-api/src/v2/utils/documentation/schedule/deleteEvent.ts, fictadvisor-api/src/v2/utils/documentation/schedule/parse.ts, fictadvisor-api/src/v2/utils/documentation/schedule/updateEvent.ts, fictadvisor-web/src/app/(main)/schedule/schedule-page/schedule-event-edit-section/ScheduleEventEdit.tsx, fictadvisor-web/src/lib/api/schedule/ScheduleAPI.ts
=> bug #605: fixed no permission exception on event update and delete

fictadvisor-web/src/app/(main)/(search-pages)/poll/[disciplineTeacherId]/components/answers-sheet/AnswersSheet.tsx, fictadvisor-web/src/app/(main)/(search-pages)/poll/[disciplineTeacherId]/page.tsx
- added autochecking for poll questions with slider
- fixed bug on reloading the page with poll form
closes #593
=> enhancement #593: added autochecking for poll questions

fictadvisor-web/src/app/(main)/(search-pages)/subjects/page.tsx, fictadvisor-web/src/app/(main)/(search-pages)/teachers/page.tsx
- fixed button for loading data on subjects and teachers pages
closes #597
=> bug #597: fixed loading more subjects

fictadvisor-api/src/main.ts, fictadvisor-api/src/v2/api/services/AuthService.ts, fictadvisor-api/src/v2/api/services/GroupService.ts, fictadvisor-api/src/v2/api/services/UserService.ts, fictadvisor-api/src/v2/mappers/RoleMapper.ts, fictadvisor-api/src/v2/utils/documentation/decorators.ts
- fixed bug with undefined selective amount
- fixed reading telegramId of undefined captain
- fixed error in mapper method
=> bug: fixed some bugs

fictadvisor-web/src/app/(auth)/login/components/login-form-block/LoginFormBlock.tsx, fictadvisor-web/src/app/(auth)/login/components/logo-register-block/LogoRegisterBlock.tsx, fictadvisor-web/src/app/(auth)/register/components/left-block/LeftBlock.tsx, fictadvisor-web/src/app/(auth)/register/components/right-block/RightBlock.tsx
- replaced old logo image on registration and authorization pages
closes #610
=> bug #610: replaced old logo image on auth pages

fictadvisor-web/src/app/(main)/account/components/general-tab/components/personal-info/PersonalInfo.tsx, fictadvisor-web/src/hooks/use-authentication/useAuthentication.tsx, fictadvisor-web/src/lib/providers/authentication/AuthenticationProvider.tsx, fictadvisor-web/src/types/authContext.ts
- added query refetching after form submit
closes #611
=> bug #611: name fields are not updated after editing

fictadvisor-api/src/v2/api/services/ScheduleService.ts, fictadvisor-api/src/v2/database/repositories/DisciplineTeacherRoleRepository.ts, fictadvisor-api/src/v2/utils/parser/CampusParser.ts, fictadvisor-api/src/v2/utils/parser/GeneralParser.ts, fictadvisor-api/src/v2/utils/parser/RozParser.ts
- replaced roz kpi parser with campus parser because of invalid creating discipline types of some events by roz parser
- removed starting of parsing before start of the semester to use campus parser
- created `aggregateParsedPairTeachers` method of campus parser for finding same pairs with different teachers and creating one event with multiple teachers
=> bug: fixed parser bugs

fictadvisor-web/src/app/admin/layout.tsx
- replaced state with variable when checking whether to redirect user
- wrapped setting of `permissionGranted` with useEffect
=> bug: fixed accessing admin panel
